export const ADD_HIGHLIGHT = 'ADD_HIGHLIGHT';
export const ACTIVATE_TOPIC = 'ACTIVATE_TOPIC';
export const NEW_ARTICLE = 'NEW_ARTICLE';
export const NEW_QUESTIONS = 'NEW_QUESTIONS';
export const DELETE_HIGHLIGHT = 'DELETE_HIGHLIGHT';
export const SELECT_HIGHLIGHT = 'SELECT_HIGHLIGHT';
